home_manager_deploy_files:
  - src: base.nix
  - src: fish.nix
  - src: git.nix
  - src: dev_tools.nix
  - src: helix.nix
  - src: zed.nix
  - src: ncspot.nix
  - src: space_tools.nix

  - src: desktop_home.nix
    mv: home.nix
