---
- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create config directories
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - grafana/provisioning/datasources/
    - mimir
    - loki

- name: Create Grafana data directory
  ansible.builtin.file:
    dest: grafana_data
    state: directory
    mode: "0755"
    owner: 472
    group: 472
  become: true

- name: Copy Mimir config
  ansible.builtin.copy:
    src: templates/mimir.yml
    dest: mimir/config.yml
    mode: "0644"
    force: true
  notify: Restart Mimir container

- name: Copy Loki config
  ansible.builtin.template:
    src: templates/loki.yml.j2
    dest: loki/config.yml
    mode: "0644"
    force: true
  notify: Restart Loki container

- name: Setup data sources in Grafana
  ansible.builtin.template:
    src: templates/datasources/monitoring.yml.j2
    dest: grafana/provisioning/datasources/monitoring.yml
    mode: "0644"
    force: true
  notify: Restart Grafana container

- name: Create Grafana network
  community.docker.docker_network:
    name: "{{ docker_grafana_setup_network }}"

- name: Run Mimir
  community.docker.docker_container:
    name: "{{ docker_grafana_setup_mimir_container }}"
    image: grafana/mimir:latest
    command: -target=all -config.file=/etc/mimir/config.yml
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_grafana_setup_network }}"
    ports:
      - "9009:9009"
    volumes:
      - ./mimir:/etc/mimir

- name: Run Loki
  community.docker.docker_container:
    name: "{{ docker_grafana_setup_loki_container }}"
    image: grafana/loki:latest
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_grafana_setup_network }}"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./loki:/etc/loki

- name: Run Grafana
  community.docker.docker_container:
    name: "{{ docker_grafana_setup_grafana_container }}"
    image: grafana/grafana:latest
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_grafana_setup_network }}"
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
