---
- name: Ensure .env file exists in home directory
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.env"
    content: ""
    mode: "0644"
    force: false

- name: Ensure Fish is the default shell for current user
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/fish
