---
- name: Ensure Fish config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/fish"
    state: directory
    mode: "0755"

- name: Copy settings files to Fish .config directory
  ansible.builtin.copy:
    src: templates/
    dest: "{{ ansible_env.HOME }}/.config/fish/"
    mode: "0655"

- name: Ensure .env file exists in home directory
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.env"
    content: ""
    mode: "0644"
    force: false

- name: Copy variables file to Fish .config directory
  ansible.builtin.copy:
    src: templates/fish_variables
    dest: "{{ ansible_env.HOME }}/.config/fish/fish_variables"
    mode: "0655"

- name: Ensure Fish is the default shell for current user
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/fish
