podman_llamacpp_gemma4_deploy_image: ghcr.io/ggml-org/llama.cpp:server-cuda13
podman_llamacpp_gemma4_deploy_container: gemma4
podman_llamacpp_gemma4_deploy_model: unsloth/gemma-4-26B-A4B-it-GGUF:UD-IQ4_XS
podman_llamacpp_gemma4_deploy_context_size: 65536
podman_llamacpp_gemma4_deploy_reasoning_budget: "{{ podman_llamacpp_gemma4_deploy_context_size | int // 16 }}"
podman_llamacpp_gemma4_deploy_gpu_layers: 2
podman_llamacpp_gemma4_deploy_threads: "{{ ansible_processor_cores }}"
