host01 ansible_host=192.168.1.10 ansible_user=jakub
host02 ansible_host=192.168.1.20 ansible_user=jakub

# VMs

# Containers
postgresql ansible_host=192.168.1.100 ansible_user=jakub
grafana ansible_host=192.168.1.200 ansible_user=jakub

[debian]
host01
host02
postgresql
grafana

[server]
host01
host02
postgresql
grafana

[proxmox]
host01
host02

[host]
host01
host02
