all:
  vars:
    ip_prefix: 192.168.69
    default_user: jakub

  hosts:
    host01:
      ansible_host: "{{ ip_prefix }}.10"
      ansible_user: "{{ default_user }}"

    host02:
      ansible_host: "{{ ip_prefix }}.20"
      ansible_user: "{{ default_user }}"

    grafana:
      ansible_host: "{{ ip_prefix }}.100"
      ansible_user: "{{ default_user }}"

    nixtest:
      ansible_host: "{{ ip_prefix }}.101"
      ansible_user: "{{ default_user }}"

    postgresql:
      ansible_host: "{{ ip_prefix }}.110"
      ansible_user: "{{ default_user }}"

    tailscale_node:
      ansible_host: "{{ ip_prefix }}.253"
      ansible_user: "{{ default_user }}"

    pihole:
      ansible_host: "{{ ip_prefix }}.254"
      ansible_user: "{{ default_user }}"

debian:
  hosts:
    host01:
    host02:
    postgresql:
    grafana:
    pihole:
    tailscale_node:
    nixtest:

server:
  hosts:
    host01:
    host02:
    postgresql:
    grafana:
    pihole:
    tailscale_node:
    nixtest:

proxmox:
  hosts:
    host01:
    host02:

host:
  hosts:
    host01:
    host02:

nixtest:
  nixtest:
