---
- name: Copy home-manager home.nix file to the target directory
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ ansible_facts.env.HOME }}/.config/home-manager/{{ item }}"
    mode: "0655"
  loop:
    - home.nix
    - fish.nix
    - helix.nix
    - git.nix
  notify: Home-manager configuration rebuild
