---
- name: Copy home-manager home.nix file to the target directory
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ ansible_facts.env.HOME }}/.config/home-manager/{{ item.mv | default(item.src, true) }}"
    mode: "0655"
  loop: "{{ home_manager_deploy_files }}"
  notify: Home-manager configuration rebuild
