home_manager_deploy_remove_garbage_older_than: 3d

home_manager_deploy_fish_shell_path: "{{ ansible_facts.env.HOME }}/.nix-profile/bin/fish"

home_manager_deploy_files:
  - src: base.nix
  - src: fish.nix
  - src: git.nix
  - src: helix.nix
  - src: dev_tools.nix

  - src: base_home.nix
    mv: home.nix

home_manager_deploy_git_user_name: >-
  {{ lookup(
       'ansible.builtin.pipe',
       'git config --global --get user.name',
       errors='ignore'
     ) | trim }}

home_manager_deploy_git_user_email: >-
  {{ lookup(
       'ansible.builtin.pipe',
       'git config --global --get user.email',
       errors='ignore'
     ) | trim }}
