home_manager_deploy_packages:
  - bat
  - eza
  - ripgrep
  - dust
  - hyperfine
  - fzf
  - fastfetch
  - git
  - zoxide
  - tmux
  - tree
  - uv
  - ruff
  - clang-tools
  - wireshark
  - ncspot
  - pipewire

home_manager_deploy_fish_aliases:
  eza: "ls"
  cat: "bat -p"
  du: "dust"

  # git aliases
  g: "git"
  gst: "git status"
  gd: "git diff"
  gdc: "git diff --cached"
  gl: "git pull"
  gup: "git pull --rebase"
  gp: "git push --force-with-lease"
  gc!: "git commit -v --amend"
  gca: "git commit -v -a"
  gca!: "git commit -v -a --amend"
  gcm: "git commit -a -m"
  gc: "git checkout"
  gr: "git remote"
  grv: "git remote -v"
  grmv: "git remote rename"
  grrm: "git remote remove"
  grset: "git remote set-url"
  grup: "git remote update"
  grbi: "git rebase -i"
  grbc: "git rebase --continue"
  grba: "git rebase --abort"
  gb: "git branch"
  gba: "git branch -a"
  gcount: "git shortlog -sn"
  gcl: "git config --list"
  gcp: "git cherry-pick"
  glg: "git log --stat --max-count=10"
  glgg: "git log --graph --max-count=10"
  glgga: "git log --graph --decorate --all"
  glo: "git log --oneline"
  gss: "git status -s"
  ga: "git add"
  gm: "git merge"
  grh: "git reset HEAD"
  grhh: "git reset HEAD --hard"
  gclean: "git reset --hard; and git clean -dfx"
  gwc: "git whatchanged -p --abbrev-commit --pretty=medium"
  gg: "git gui citool"
  gga: "git gui citool --amend"
  gk: "gitk --all --branches"
  gsts: "git stash show --text"
  gsta: "git stash"
  gstp: "git stash pop"
  gstd: "git stash drop"
