---
- name: Ensure model directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ ansible_facts.env.HOME }}/llamacpp/cache"
    - "{{ ansible_facts.env.HOME }}/llamacpp/prompts"

- name: Copy system promopt to model directory
  ansible.builtin.copy:
    src: templates/system.txt
    dest: "{{ ansible_facts.env.HOME }}/llamacpp/prompts/system.txt"
    mode: "0644"

- name: Install container definitions
  ansible.builtin.template:
    src: templates/{{ item }}.container.j2
    dest: /etc/containers/systemd/{{ item }}.container
    mode: "0644"
  become: true
  loop:
    - "{{ podman_llamacpp_deploy_gemma4_container }}"
    - "{{ podman_llamacpp_deploy_qwen36_container }}"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Enable llammacpp containers
  ansible.builtin.systemd:
    name: "{{ item }}.service"
    enabled: true
    state: stopped
  become: true
  loop:
    - "{{ podman_llamacpp_deploy_gemma4_container }}"
    - "{{ podman_llamacpp_deploy_qwen36_container }}"
