---
- name: Ensure model directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ ansible_facts.env.HOME }}/llamacpp/cache"
    - "{{ ansible_facts.env.HOME }}/llamacpp/prompts"

- name: Copy system prompt to model directory
  ansible.builtin.copy:
    src: templates/system.txt
    dest: "{{ ansible_facts.env.HOME }}/llamacpp/prompts/system.txt"
    mode: "0644"

- name: Install container definitions
  ansible.builtin.template:
    src: templates/llamacpp.container.j2
    dest: /etc/containers/systemd/{{ item.name }}.container
    mode: "0644"
  become: true
  loop: "{{ podman_llamacpp_deploy_models }}"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Enable llamacpp containers
  ansible.builtin.systemd:
    name: "{{ item.name }}.service"
    enabled: true
    state: stopped
  become: true
  loop: "{{ podman_llamacpp_deploy_models }}"
