---
- name: Ensure model directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ ansible_facts.env.HOME }}/llamacpp/cache"
    - "{{ ansible_facts.env.HOME }}/llamacpp/prompts"

- name: Discover GPU VRAM
  ansible.builtin.command:
    cmd: nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits
  register: podman_llamacpp_deploy_nvidia_vram
  changed_when: false

- name: Set llama.cpp context size based on VRAM
  ansible.builtin.set_fact:
    podman_llamacpp_deploy_context_size: >-
      {{ 32768 if (podman_llamacpp_deploy_nvidia_vram.stdout | int) < 4096 else 49152 }}

- name: Install container definitions
  ansible.builtin.template:
    src: templates/llamacpp.container.j2
    dest: /etc/containers/systemd/{{ item.name }}.container
    mode: "0644"
  become: true
  loop: "{{ podman_llamacpp_deploy_models }}"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Disable llamacpp containers
  ansible.builtin.systemd:
    name: "{{ item.name }}.service"
    enabled: true
    state: stopped
  become: true
  loop: "{{ podman_llamacpp_deploy_models }}"
