---
- name: Check whether Nix is already installed
  ansible.builtin.stat:
    path: /nix/var/nix/profiles/default/bin/nix
  register: nix_installed

- name: Download Nix installer
  ansible.builtin.get_url:
    url: "{{ nix_installer_url }}"
    dest: "{{ nix_installer_path }}"
    mode: "0755"
  when: not nix_installed.stat.exists

- name: Install Nix
  ansible.builtin.command:
    cmd: "{{ nix_installer_path }} {{ nix_install_args | join(' ') }}"
  environment:
    NIX_INSTALLER_NO_MODIFY_PROFILE: "1"
  when: not nix_installed.stat.exists

- name: Remove Nix installer
  ansible.builtin.file:
    path: "{{ nix_installer_path }}"
    state: absent
