---
- name: Ensure Gnome Extensions directory exists.
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/gnome-shell/extensions"
    state: directory
    mode: "0755"

- name: Copy extenisons config to the correct directory
  ansible.builtin.copy:
    src: templates/extensions/
    dest: "{{ ansible_env.HOME }}/.local/share/gnome-shell/extensions/"
    mode: "0655"
