---
- name: Disable password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  become: true

- name: Ensure the .ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.ssh/"
    state: directory
    mode: "0700"

- name: Copy authorized_keys file to the .ssh directory
  ansible.builtin.copy:
    src: templates/
    dest: "{{ ansible_facts.env.HOME }}/.ssh/"
    mode: "0600"

- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: true
