---
- name: Remove existing nvim config
  ansible.builtin.file:
    path: ~/.config/nvim
    state: absent

- name: Install AstroVim
  ansible.builtin.git:
    repo: https://github.com/AstroNvim/template
    dest: ~/.config/nvim
    depth: 1
    version: main
