---
- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Run cAdvisor container
  community.docker.docker_container:
    name: "{{ docker_cadvisor_setup_container_name }}"
    image: "{{ docker_cadvisor_setup_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ docker_cadvisor_setup_port }}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
