name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install community.general in ansible-galaxy
        run: uv run ansible-galaxy collection install -r requirements.yml

      - name: Validate ansible config
        run: uv run ansible-config validate

      - name: Run ansible-lint
        run: uv run ansible-lint *.yml
